/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AppConfig": {
      "apiUrl": string
      "appScheme": string
      "authFromEmail": string
      "corsOrigins": any
      "dev": boolean
      "type": "sst.sst.Linkable"
      "webUrl": string
    }
    "BlockedMints": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CongressApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeliusApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JupiterApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenaiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivyAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivyAppSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivyClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PythApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SolanaPaymasterKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StockpileLanding": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "TokensApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}