/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": import("@cloudflare/workers-types").Service
    "AppConfig": {
      "apiUrl": string
      "appScheme": string
      "authFromEmail": string
      "dev": boolean
      "type": "sst.sst.Linkable"
      "webUrl": string
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": import("@cloudflare/workers-types").Hyperdrive
    "DatabaseHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabasePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}
