/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "Backend": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "BridgeApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BridgeWebhookPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabasePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GridApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeliusApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeliusRpcUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JupiterApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PdfGenerator": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "PdfLambdaUrl": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "PlatformFeeWallet": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivyAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivyAppSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SolanaPaymaster": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SolanaTrackerApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SoljarLanding": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "SoljarPay": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "TxMessageSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}