/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BagsRouteImport } from './routes/bags'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SellTokensRouteImport } from './routes/sell-tokens'
import { Route as AssetSymbolRouteImport } from './routes/asset.$symbol'
import { Route as BagIdRouteImport } from './routes/bag.$id'
import { Route as BuyBagIdRouteImport } from './routes/buy.$bagId'
import { Route as SellTokensIndexRouteImport } from './routes/sell-tokens.index'
import { Route as SellTokensProgressRouteImport } from './routes/sell-tokens.progress'
import { Route as SellTokensReviewRouteImport } from './routes/sell-tokens.review'
import { Route as SellBagIdRouteImport } from './routes/sell.$bagId'
import { Route as BuyBagIdIndexRouteImport } from './routes/buy.$bagId.index'
import { Route as BuyBagIdProgressRouteImport } from './routes/buy.$bagId.progress'
import { Route as BuyBagIdReviewRouteImport } from './routes/buy.$bagId.review'
import { Route as SellBagIdIndexRouteImport } from './routes/sell.$bagId.index'
import { Route as SellBagIdProgressRouteImport } from './routes/sell.$bagId.progress'
import { Route as SellBagIdReviewRouteImport } from './routes/sell.$bagId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsRoute = BagsRouteImport.update({
  id: '/bags',
  path: '/bags',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SellTokensRoute = SellTokensRouteImport.update({
  id: '/sell-tokens',
  path: '/sell-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetSymbolRoute = AssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const BagIdRoute = BagIdRouteImport.update({
  id: '/bag/$id',
  path: '/bag/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyBagIdRoute = BuyBagIdRouteImport.update({
  id: '/buy/$bagId',
  path: '/buy/$bagId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellTokensIndexRoute = SellTokensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellTokensRoute,
} as any)
const SellTokensProgressRoute = SellTokensProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => SellTokensRoute,
} as any)
const SellTokensReviewRoute = SellTokensReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SellTokensRoute,
} as any)
const SellBagIdRoute = SellBagIdRouteImport.update({
  id: '/sell/$bagId',
  path: '/sell/$bagId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyBagIdIndexRoute = BuyBagIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyBagIdRoute,
} as any)
const BuyBagIdProgressRoute = BuyBagIdProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => BuyBagIdRoute,
} as any)
const BuyBagIdReviewRoute = BuyBagIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => BuyBagIdRoute,
} as any)
const SellBagIdIndexRoute = SellBagIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellBagIdRoute,
} as any)
const SellBagIdProgressRoute = SellBagIdProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => SellBagIdRoute,
} as any)
const SellBagIdReviewRoute = SellBagIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SellBagIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bags': typeof BagsRoute
  '/portfolio': typeof PortfolioRoute
  '/saved': typeof SavedRoute
  '/sell-tokens': typeof SellTokensRouteWithChildren
  '/asset/$symbol': typeof AssetSymbolRoute
  '/bag/$id': typeof BagIdRoute
  '/buy/$bagId': typeof BuyBagIdRouteWithChildren
  '/sell-tokens/progress': typeof SellTokensProgressRoute
  '/sell-tokens/review': typeof SellTokensReviewRoute
  '/sell/$bagId': typeof SellBagIdRouteWithChildren
  '/sell-tokens/': typeof SellTokensIndexRoute
  '/buy/$bagId/progress': typeof BuyBagIdProgressRoute
  '/buy/$bagId/review': typeof BuyBagIdReviewRoute
  '/sell/$bagId/progress': typeof SellBagIdProgressRoute
  '/sell/$bagId/review': typeof SellBagIdReviewRoute
  '/buy/$bagId/': typeof BuyBagIdIndexRoute
  '/sell/$bagId/': typeof SellBagIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bags': typeof BagsRoute
  '/portfolio': typeof PortfolioRoute
  '/saved': typeof SavedRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/bag/$id': typeof BagIdRoute
  '/sell-tokens/progress': typeof SellTokensProgressRoute
  '/sell-tokens/review': typeof SellTokensReviewRoute
  '/sell-tokens': typeof SellTokensIndexRoute
  '/buy/$bagId/progress': typeof BuyBagIdProgressRoute
  '/buy/$bagId/review': typeof BuyBagIdReviewRoute
  '/sell/$bagId/progress': typeof SellBagIdProgressRoute
  '/sell/$bagId/review': typeof SellBagIdReviewRoute
  '/buy/$bagId': typeof BuyBagIdIndexRoute
  '/sell/$bagId': typeof SellBagIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bags': typeof BagsRoute
  '/portfolio': typeof PortfolioRoute
  '/saved': typeof SavedRoute
  '/sell-tokens': typeof SellTokensRouteWithChildren
  '/asset/$symbol': typeof AssetSymbolRoute
  '/bag/$id': typeof BagIdRoute
  '/buy/$bagId': typeof BuyBagIdRouteWithChildren
  '/sell-tokens/progress': typeof SellTokensProgressRoute
  '/sell-tokens/review': typeof SellTokensReviewRoute
  '/sell/$bagId': typeof SellBagIdRouteWithChildren
  '/sell-tokens/': typeof SellTokensIndexRoute
  '/buy/$bagId/progress': typeof BuyBagIdProgressRoute
  '/buy/$bagId/review': typeof BuyBagIdReviewRoute
  '/sell/$bagId/progress': typeof SellBagIdProgressRoute
  '/sell/$bagId/review': typeof SellBagIdReviewRoute
  '/buy/$bagId/': typeof BuyBagIdIndexRoute
  '/sell/$bagId/': typeof SellBagIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bags'
    | '/portfolio'
    | '/saved'
    | '/sell-tokens'
    | '/asset/$symbol'
    | '/bag/$id'
    | '/buy/$bagId'
    | '/sell-tokens/progress'
    | '/sell-tokens/review'
    | '/sell/$bagId'
    | '/sell-tokens/'
    | '/buy/$bagId/progress'
    | '/buy/$bagId/review'
    | '/sell/$bagId/progress'
    | '/sell/$bagId/review'
    | '/buy/$bagId/'
    | '/sell/$bagId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bags'
    | '/portfolio'
    | '/saved'
    | '/asset/$symbol'
    | '/bag/$id'
    | '/sell-tokens/progress'
    | '/sell-tokens/review'
    | '/sell-tokens'
    | '/buy/$bagId/progress'
    | '/buy/$bagId/review'
    | '/sell/$bagId/progress'
    | '/sell/$bagId/review'
    | '/buy/$bagId'
    | '/sell/$bagId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bags'
    | '/portfolio'
    | '/saved'
    | '/sell-tokens'
    | '/asset/$symbol'
    | '/bag/$id'
    | '/buy/$bagId'
    | '/sell-tokens/progress'
    | '/sell-tokens/review'
    | '/sell/$bagId'
    | '/sell-tokens/'
    | '/buy/$bagId/progress'
    | '/buy/$bagId/review'
    | '/sell/$bagId/progress'
    | '/sell/$bagId/review'
    | '/buy/$bagId/'
    | '/sell/$bagId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BagsRoute: typeof BagsRoute
  PortfolioRoute: typeof PortfolioRoute
  SavedRoute: typeof SavedRoute
  SellTokensRoute: typeof SellTokensRouteWithChildren
  AssetSymbolRoute: typeof AssetSymbolRoute
  BagIdRoute: typeof BagIdRoute
  BuyBagIdRoute: typeof BuyBagIdRouteWithChildren
  SellBagIdRoute: typeof SellBagIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags': {
      id: '/bags'
      path: '/bags'
      fullPath: '/bags'
      preLoaderRoute: typeof BagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-tokens': {
      id: '/sell-tokens'
      path: '/sell-tokens'
      fullPath: '/sell-tokens'
      preLoaderRoute: typeof SellTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$symbol': {
      id: '/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag/$id': {
      id: '/bag/$id'
      path: '/bag/$id'
      fullPath: '/bag/$id'
      preLoaderRoute: typeof BagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$bagId': {
      id: '/buy/$bagId'
      path: '/buy/$bagId'
      fullPath: '/buy/$bagId'
      preLoaderRoute: typeof BuyBagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-tokens/': {
      id: '/sell-tokens/'
      path: '/'
      fullPath: '/sell-tokens/'
      preLoaderRoute: typeof SellTokensIndexRouteImport
      parentRoute: typeof SellTokensRoute
    }
    '/sell-tokens/progress': {
      id: '/sell-tokens/progress'
      path: '/progress'
      fullPath: '/sell-tokens/progress'
      preLoaderRoute: typeof SellTokensProgressRouteImport
      parentRoute: typeof SellTokensRoute
    }
    '/sell-tokens/review': {
      id: '/sell-tokens/review'
      path: '/review'
      fullPath: '/sell-tokens/review'
      preLoaderRoute: typeof SellTokensReviewRouteImport
      parentRoute: typeof SellTokensRoute
    }
    '/sell/$bagId': {
      id: '/sell/$bagId'
      path: '/sell/$bagId'
      fullPath: '/sell/$bagId'
      preLoaderRoute: typeof SellBagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$bagId/': {
      id: '/buy/$bagId/'
      path: '/'
      fullPath: '/buy/$bagId/'
      preLoaderRoute: typeof BuyBagIdIndexRouteImport
      parentRoute: typeof BuyBagIdRoute
    }
    '/buy/$bagId/progress': {
      id: '/buy/$bagId/progress'
      path: '/progress'
      fullPath: '/buy/$bagId/progress'
      preLoaderRoute: typeof BuyBagIdProgressRouteImport
      parentRoute: typeof BuyBagIdRoute
    }
    '/buy/$bagId/review': {
      id: '/buy/$bagId/review'
      path: '/review'
      fullPath: '/buy/$bagId/review'
      preLoaderRoute: typeof BuyBagIdReviewRouteImport
      parentRoute: typeof BuyBagIdRoute
    }
    '/sell/$bagId/': {
      id: '/sell/$bagId/'
      path: '/'
      fullPath: '/sell/$bagId/'
      preLoaderRoute: typeof SellBagIdIndexRouteImport
      parentRoute: typeof SellBagIdRoute
    }
    '/sell/$bagId/progress': {
      id: '/sell/$bagId/progress'
      path: '/progress'
      fullPath: '/sell/$bagId/progress'
      preLoaderRoute: typeof SellBagIdProgressRouteImport
      parentRoute: typeof SellBagIdRoute
    }
    '/sell/$bagId/review': {
      id: '/sell/$bagId/review'
      path: '/review'
      fullPath: '/sell/$bagId/review'
      preLoaderRoute: typeof SellBagIdReviewRouteImport
      parentRoute: typeof SellBagIdRoute
    }
  }
}

interface SellTokensRouteChildren {
  SellTokensProgressRoute: typeof SellTokensProgressRoute
  SellTokensReviewRoute: typeof SellTokensReviewRoute
  SellTokensIndexRoute: typeof SellTokensIndexRoute
}

const SellTokensRouteChildren: SellTokensRouteChildren = {
  SellTokensProgressRoute: SellTokensProgressRoute,
  SellTokensReviewRoute: SellTokensReviewRoute,
  SellTokensIndexRoute: SellTokensIndexRoute,
}

const SellTokensRouteWithChildren = SellTokensRoute._addFileChildren(
  SellTokensRouteChildren,
)

interface BuyBagIdRouteChildren {
  BuyBagIdProgressRoute: typeof BuyBagIdProgressRoute
  BuyBagIdReviewRoute: typeof BuyBagIdReviewRoute
  BuyBagIdIndexRoute: typeof BuyBagIdIndexRoute
}

const BuyBagIdRouteChildren: BuyBagIdRouteChildren = {
  BuyBagIdProgressRoute: BuyBagIdProgressRoute,
  BuyBagIdReviewRoute: BuyBagIdReviewRoute,
  BuyBagIdIndexRoute: BuyBagIdIndexRoute,
}

const BuyBagIdRouteWithChildren = BuyBagIdRoute._addFileChildren(
  BuyBagIdRouteChildren,
)

interface SellBagIdRouteChildren {
  SellBagIdProgressRoute: typeof SellBagIdProgressRoute
  SellBagIdReviewRoute: typeof SellBagIdReviewRoute
  SellBagIdIndexRoute: typeof SellBagIdIndexRoute
}

const SellBagIdRouteChildren: SellBagIdRouteChildren = {
  SellBagIdProgressRoute: SellBagIdProgressRoute,
  SellBagIdReviewRoute: SellBagIdReviewRoute,
  SellBagIdIndexRoute: SellBagIdIndexRoute,
}

const SellBagIdRouteWithChildren = SellBagIdRoute._addFileChildren(
  SellBagIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BagsRoute: BagsRoute,
  PortfolioRoute: PortfolioRoute,
  SavedRoute: SavedRoute,
  SellTokensRoute: SellTokensRouteWithChildren,
  AssetSymbolRoute: AssetSymbolRoute,
  BagIdRoute: BagIdRoute,
  BuyBagIdRoute: BuyBagIdRouteWithChildren,
  SellBagIdRoute: SellBagIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
