/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_API_URL: string
  readonly VITE_PRIVY_APP_ID: string
  readonly VITE_PRIVY_CLIENT_ID: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}